### ISSUE TITLE
检查具有铸币功能的合约

### ISSUE THREAD

**Issue by easyforgood** [sec-bit/adelaide#2]
## backgroud

有些交易所例如 DDEX，不允许具有随意铸币功能的合约上交易所，并且这些能够铸币的合约有一些特征，因此可以让 checker 进行自动化的检查，提高审计效率。

## 特点

一般这些合约有如下特点：
- 方法名具有关键词  mint。
- totalSupply 总量会增加。

## 参考合约

- BurnableCrowdsaleToken_0xc15a399c4ea7815fe36857c9e290ee452a5d6b21 
- HadeCoin_0x7b171c08d812f9c642dcf61f7e080610cbca64b3
- MorphToken_0x2ef27bf41236bd859a95209e17a43fbd26851f92
- METToken_0xa3d58c4e56fedcae3a7c43a725aee9a71f0ece4e
- XmxToken_0x0f8c45b896784a1e408526b9300519ef8660209c

**Comment by depedro** [comment]
Signatures:
1) function `/$_?mint.*^/`
2) constructor argument `/_?mintable/`
3) `totalSupply +=`  or `totalSupply = totalSupply +`
