### ISSUE TITLE
扫描特定合约时，adelaide进程会一直卡死。

### ISSUE THREAD

**Issue by easyforgood** [sec-bit/adelaide#4]
RT，扫描该合约的时候出现问题：
https://etherscan.io/address/0x6329316475a98027e62246d25e4a5ed8d7f9fc51#code

**Comment by p0n1** [comment]
https://etherscan.io/address/0xb9e31a22e3a1c743c6720f3b723923e91f3c0f8b#code

这个合约也会卡住

**Comment by depedro** [comment]
> https://etherscan.io/address/0xb9e31a22e3a1c743c6720f3b723923e91f3c0f8b#code
> 
> 这个合约也会卡住

$ time ~/secbit/adelaide/build/solc/solc --secbit-warnings a.json -o . --overwrite test.sol

real    1m53.034s
user    1m52.484s
sys     0m0.047s

最后还是算出来了。。。

**Comment by depedro** [comment]
This should have been fixed by cherry-picking commit b356f6a from develop branch, which sets a 10 second timeout for the solver.

**Comment by depedro** [comment]
This would require a newer version of z3 though, tested 4.6.0 and 4.8.1, both worked fine.
